/**
 * Supabase Database Type Definitions
 *
 * This file contains auto-generated TypeScript type definitions for the FinBuddy application's
 * Supabase database schema. These types provide full type safety for database operations,
 * ensuring that queries, inserts, and updates are validated at compile time.
 *
 * Generated by: Supabase CLI
 * Purpose: Type-safe database interactions
 * Schema: FinBuddy financial tracking application
 */

/**
 * Recursive JSON type definition
 * Represents all possible JSON values that can be stored in PostgreSQL JSON/JSONB columns
 */
export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined } // JSON objects with optional properties
  | Json[] // JSON arrays

/**
 * Complete database schema type definition
 * Defines the structure of the entire Supabase database including tables, views, functions, etc.
 */
export type Database = {
  // Internal Supabase metadata for client instantiation
  // Allows automatic client creation with correct PostgREST version
  __InternalSupabase: {
    PostgrestVersion: "14.1"
  }

  // Public schema containing all application data
  public: {
    // Database tables and their type definitions
    Tables: {
      /**
       * Notifications table - stores user notifications and alerts
       * Used for real-time notifications about spending, reminders, etc.
       */
      notifications: {
        /** Complete row data as returned from SELECT queries */
        Row: {
          created_at: string    // ISO timestamp when notification was created
          dismissed: boolean    // Whether user has dismissed this notification
          id: string           // Unique notification identifier (UUID)
          level: string        // Notification severity ('info', 'warning', 'error', etc.)
          message: string      // Notification message text
          user_id: string      // ID of user who owns this notification
        }
        /** Data required for INSERT operations (some fields auto-generated) */
        Insert: {
          created_at?: string   // Optional, defaults to current timestamp
          dismissed?: boolean   // Optional, defaults to false
          id?: string          // Optional, auto-generated UUID
          level?: string       // Optional, defaults to 'info'
          message: string      // Required: notification message
          user_id: string      // Required: user identifier
        }
        /** Data allowed for UPDATE operations (all fields optional) */
        Update: {
          created_at?: string
          dismissed?: boolean
          id?: string
          level?: string
          message?: string
          user_id?: string
        }
        /** Foreign key relationships (empty in this schema) */
        Relationships: []
      }

      /**
       * User profiles table - stores user account settings and preferences
       * Contains personalization data like budget, currency, and notification preferences
       */
      profiles: {
        /** Complete profile data structure */
        Row: {
          avatar_url: string | null     // User's profile picture URL
          created_at: string           // Account creation timestamp
          currency: string             // User's preferred currency code (e.g., 'USD', 'EUR')
          display_name: string | null   // User's display name
          email_daily_reminders: boolean // Whether to send daily spending reminders
          email_overspending_alerts: boolean // Whether to send budget alerts
          id: string                  // Profile record ID (UUID)
          monthly_budget: number | null // User's monthly spending budget
          updated_at: string          // Last profile update timestamp
          user_id: string             // Associated Supabase auth user ID
        }
        /** Required data for creating new profiles */
        Insert: {
          avatar_url?: string | null
          created_at?: string
          currency?: string            // Defaults to application default
          display_name?: string | null
          email_daily_reminders?: boolean // Defaults to true
          email_overspending_alerts?: boolean // Defaults to true
          id?: string                 // Auto-generated
          monthly_budget?: number | null
          updated_at?: string
          user_id: string             // Required: links to auth user
        }
        /** Allowed fields for profile updates */
        Update: {
          avatar_url?: string | null
          created_at?: string
          currency?: string
          display_name?: string | null
          email_daily_reminders?: boolean
          email_overspending_alerts?: boolean
          id?: string
          monthly_budget?: number | null
          updated_at?: string
          user_id?: string
        }
        /** No foreign key relationships defined */
        Relationships: []
      }

      /**
       * Transactions table - stores all financial transactions
       * Core table containing expense and income records for budget tracking
       */
      transactions: {
        /** Complete transaction record structure */
        Row: {
          amount: number        // Transaction amount (positive for income, negative for expenses)
          category: string      // Transaction category (e.g., 'Food', 'Transportation')
          created_at: string    // Record creation timestamp
          date: string          // Transaction date (YYYY-MM-DD format)
          description: string   // Transaction description/details
          flagged: boolean | null // Whether transaction needs review
          id: string           // Unique transaction identifier (UUID)
          user_id: string      // ID of user who owns this transaction
        }
        /** Required data for creating new transactions */
        Insert: {
          amount: number        // Required: transaction amount
          category?: string     // Optional, can be auto-categorized
          created_at?: string   // Optional, defaults to current timestamp
          date?: string         // Optional, defaults to today
          description: string   // Required: transaction description
          flagged?: boolean | null // Optional, defaults to false
          id?: string          // Optional, auto-generated UUID
          user_id: string      // Required: user identifier
        }
        /** Allowed fields for transaction updates */
        Update: {
          amount?: number
          category?: string
          created_at?: string
          date?: string
          description?: string
          flagged?: boolean | null
          id?: string
          user_id?: string
        }
        /** No foreign key relationships defined */
        Relationships: []
      }
    }

    // Database views (none defined in this schema)
    Views: {
      [_ in never]: never
    }

    // Database functions (none defined in this schema)
    Functions: {
      [_ in never]: never
    }

    // Database enums (none defined in this schema)
    Enums: {
      [_ in never]: never
    }

    // Composite types (none defined in this schema)
    CompositeTypes: {
      [_ in never]: never
    }
  }
}

/**
 * Utility type: Database schema without internal Supabase metadata
 * Used for cleaner type operations by removing internal fields
 */
type DatabaseWithoutInternals = Omit<Database, "__InternalSupabase">

/**
 * Utility type: Default public schema reference
 * Provides easy access to the public schema tables and types
 */
type DefaultSchema = DatabaseWithoutInternals[Extract<keyof Database, "public">]

/**
 * Type helper: Extract row types from database tables
 * Provides type-safe access to table row data
 *
 * Usage: Tables<'transactions'> returns the Row type for transactions table
 */
export type Tables<
  DefaultSchemaTableNameOrOptions extends
    | keyof (DefaultSchema["Tables"] & DefaultSchema["Views"])
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
        DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
      DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])[TableName] extends {
      Row: infer R
    }
    ? R
    : never
  : DefaultSchemaTableNameOrOptions extends keyof (DefaultSchema["Tables"] &
        DefaultSchema["Views"])
    ? (DefaultSchema["Tables"] &
        DefaultSchema["Views"])[DefaultSchemaTableNameOrOptions] extends {
        Row: infer R
      }
      ? R
      : never
    : never

/**
 * Type helper: Extract insert types from database tables
 * Provides type-safe data structures for INSERT operations
 *
 * Usage: TablesInsert<'transactions'> returns the Insert type for transactions table
 */
export type TablesInsert<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Insert: infer I
    }
    ? I
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Insert: infer I
      }
      ? I
      : never
    : never

/**
 * Type helper: Extract update types from database tables
 * Provides type-safe data structures for UPDATE operations
 *
 * Usage: TablesUpdate<'transactions'> returns the Update type for transactions table
 */
export type TablesUpdate<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Update: infer U
    }
    ? U
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Update: infer U
      }
      ? U
      : never
    : never

/**
 * Type helper: Extract enum types from database
 * Provides access to database enum definitions (none defined in this schema)
 */
export type Enums<
  DefaultSchemaEnumNameOrOptions extends
    | keyof DefaultSchema["Enums"]
    | { schema: keyof DatabaseWithoutInternals },
  EnumName extends DefaultSchemaEnumNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"]
    : never = never,
> = DefaultSchemaEnumNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"][EnumName]
  : DefaultSchemaEnumNameOrOptions extends keyof DefaultSchema["Enums"]
    ? DefaultSchema["Enums"][DefaultSchemaEnumNameOrOptions]
    : never

/**
 * Type helper: Extract composite types from database
 * Provides access to database composite type definitions (none defined in this schema)
 */
export type CompositeTypes<
  PublicCompositeTypeNameOrOptions extends
    | keyof DefaultSchema["CompositeTypes"]
    | { schema: keyof DatabaseWithoutInternals },
  CompositeTypeName extends PublicCompositeTypeNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"]
    : never = never,
> = PublicCompositeTypeNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"][CompositeTypeName]
  : PublicCompositeTypeNameOrOptions extends keyof DefaultSchema["CompositeTypes"]
    ? DefaultSchema["CompositeTypes"][PublicCompositeTypeNameOrOptions]
    : never

/**
 * Database constants
 * Contains enum values and other database constants (empty in this schema)
 */
export const Constants = {
  public: {
    Enums: {},
  },
} as const
